# Generated by Orun 0.0.1.dev20160824141641 on 2016-08-24 14:16
from orun.db import migrations, models
import orun.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateSchema(
            name='product',
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(null=False, primary_key=True)),
                ('name', models.CharField(max_length=128, null=False)),
            ],
            options={
                'name': 'product.attribute',
                'db_table': '"product"."attribute"',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(null=False, primary_key=True)),
                ('name', models.CharField(max_length=128, null=False)),
            ],
            options={
                'name': 'product.attribute.value',
                'db_table': '"product"."attribute_value"',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(null=False, primary_key=True)),
                ('name', models.CharField(max_length=128, null=False)),
            ],
            options={
                'name': 'product.category',
                'db_table': '"product"."category"',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(null=False, primary_key=True)),
            ],
            options={
                'name': 'product.item',
                'db_table': '"product"."item"',
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(null=False, primary_key=True)),
                ('name', models.CharField(max_length=128, null=False)),
            ],
            options={
                'name': 'product.packaging',
                'db_table': '"product"."packaging"',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('test', models.CharField(max_length=128)),
            ],
            options={
                'name': 'res.partner',
                'db_table': 'res_partner',
                'extension': True,
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(null=False, primary_key=True)),
                ('name', models.CharField(max_length=128, null=False)),
                ('active', models.BooleanField(null=False)),
                ('currency', models.ForeignKey(on_delete=orun.db.models.deletion.CASCADE, to='res.currency')),
            ],
            options={
                'name': 'product.price.list',
                'db_table': '"product"."price_list"',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(null=False, primary_key=True)),
                ('name', models.CharField(max_length=128, null=False)),
                ('active', models.BooleanField(null=False)),
                ('rental', models.BooleanField(null=False)),
                ('sale_ok', models.BooleanField(null=False)),
                ('state', models.CharField(max_length=128)),
                ('color', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=orun.db.models.deletion.CASCADE, to='product.category')),
                ('manager', models.ForeignKey(on_delete=orun.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'name': 'product.template',
                'db_table': '"product"."template"',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(null=False, primary_key=True)),
                ('name', models.CharField(max_length=128, null=False)),
                ('active', models.BooleanField(null=False)),
                ('rounding', models.FloatField()),
                ('factor', models.FloatField()),
                ('unit_type', models.CharField(max_length=128)),
            ],
            options={
                'name': 'product.unit',
                'db_table': '"product"."unit"',
            },
        ),
        migrations.CreateModel(
            name='UnitCategory',
            fields=[
                ('id', models.BigAutoField(null=False, primary_key=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'name': 'product.unit.category',
                'db_table': '"product"."unit_category"',
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='category',
            field=models.ForeignKey(on_delete=orun.db.models.deletion.CASCADE, to='product.unit.category'),
        ),
        migrations.AddField(
            model_name='template',
            name='purchase_unit',
            field=models.ForeignKey(on_delete=orun.db.models.deletion.CASCADE, to='product.unit'),
        ),
        migrations.AddField(
            model_name='template',
            name='sale_unit',
            field=models.ForeignKey(on_delete=orun.db.models.deletion.CASCADE, to='product.unit'),
        ),
        migrations.AddField(
            model_name='item',
            name='template',
            field=models.ForeignKey(null=False, on_delete=orun.db.models.deletion.CASCADE, to='product.template'),
        ),
    ]
